### ISSUE TITLE
Support for calling functions without any arguments

### ISSUE THREAD

**Issue by americast** [georgia-tech-db/evadb#1121]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

There might be a need to call a function without any arguments. Currently, calling `SELECT <function>() FROM <table>;` gives this error:

```
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('RR_BRACKET', ')') at line 1, column 17.
Expected one of: 
        * MAX
        * AVG
        * DECIMAL_LITERAL
        * SUM
        * ONE_DECIMAL
        * MINUS
        * LR_SQ_BRACKET
        * LR_BRACKET
        * COUNT
        * BIT_NOT_OP
        * TRUE
        * FALSE
        * LOCAL_ID
        * STRING_LITERAL
        * TWO_DECIMAL
        * SEGMENT
        * STAR
        * REVERSE_QUOTE_ID
        * PLUS
        * ID
        * MIN
        * FIRST
        * REAL_LITERAL
        * ANYDIM
        * NOT
        * LAST
        * EXCLAMATION_SYMBOL
        * ZERO_DECIMAL
Previous tokens: [Token('LR_BRACKET', '(')]
```

while calling `SELECT <function>();` results in

```
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('RR_BRACKET', ')') at line 1, column 17.
Expected one of: 
        * ONE_DECIMAL
        * LR_SQ_BRACKET
        * COUNT
        * SEGMENT
        * STRING_LITERAL
        * MIN
        * STAR
        * TRUE
        * LR_BRACKET
        * NOT
        * FIRST
        * REAL_LITERAL
        * BIT_NOT_OP
        * LAST
        * ZERO_DECIMAL
        * PLUS
        * REVERSE_QUOTE_ID
        * FALSE
        * MINUS
        * AVG
        * ANYDIM
        * LOCAL_ID
        * SUM
        * DECIMAL_LITERAL
        * ID
        * MAX
        * TWO_DECIMAL
        * EXCLAMATION_SYMBOL
Previous tokens: [Token('LR_BRACKET', '(')]
```

### Use case

We expect to call `SELECT <function>();` without any error. It will help call functions that are specific to data when they are created.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
@xzdandy This is fixed, right?

**Comment by gaurav274** [comment]
@americast @xzdandy Are we going to go with `SELECT <function>();` or `SELECT <function>() from table;`?

**Comment by xzdandy** [comment]
This is not fixed. For now `SELECT <function>();` is recommended.  We need optimize `SELECT <function>() from table;` so if it does not actually read the table (when the table is large it can take time). To systemically support it, it can be non trivial.

**Comment by xzdandy** [comment]
The problem can be reproduced using the following dummy function and queries:

Function defined in test/util.py:
```
class DummyNoInputFunction(AbstractFunction):
    @decorators.setup(cacheable=False, function_type="test", batchable=False)
    def setup(self, *args, **kwargs):
        pass

    @property
    def name(self) -> str:
        return "DummyNoInputFunction"

    @decorators.forward(
        input_signatures = [],
        output_signatures = [
            PandasDataframe(
                columns = ["label"],
                column_types = [NdArrayType.STR],
                column_shapes = [(None,)],
            )
        ],
    )
    def forward(self, df: pd.DataFrame) -> pd.DataFrame:
        ret = pd.DataFrame([{"label": "DummyNoInputFunction"}])
        return ret
```

Queries:
```
import evadb
cursor = evadb.connect().cursor()

df = cursor.query("""
    CREATE OR REPLACE FUNCTION DummyNoInputFunction
    IMPL 'test/util.py'
""").df()
print(df)

df = cursor.query("SELECT DummyNoInputFunction();").df()
print(df)
```
Looking into the fix now.
